export const COMPLETE_ASSIGNMENT = "COMPLETE_ASSIGNMENT";
export const UPDATE_ASSIGNMENT_TYPE = "UPDATE_ASSIGNMENT_TYPE";
export const UPDATE_ASSIGNMENT_DIFFICULTY = "UPDATE_ASSIGNMENT_DIFFICULTY";
export const UPDATE_ASSIGNMENT_REMINDER = "UPDATE_ASSIGNMENT_REMINDER";
export const ADD_ASSIGNMENT_REMINDER = "ADD_ASSIGNMENT_REMINDER";

export const GET_ASSIGNMENTS = "LIST_ASSIGNMENTS";
export const SET_ASSIGNMENTS_LIST = "SET_ASSIGNMENTS_LIST";
export const RESET = "RESET";

export const SET_USER_DATA = "SET_USER_DATA";
export const FETCH_USER_DATA = "FETCH_USER_DATA";
export const SET_IS_LOGGED_IN = "SET_IS_LOGGED_IN";

export const SET_CALENDAR_DATA = "SET_CALENDAR_DATA";
export const GET_CALENDAR_DATA = "GET_CALENDAR_DATA";
export const SET_CALENDAR_ID = "SET_CALENDAR_ID";

export const SET_WEIGHTS = "SET_WEIGHTS";
export const SET_USER_WEIGHTS = "SET_USER_WEIGHTS";

export const UPDATE_ASSIGNMENT_REMINDER_ARRAY =
  "UPDATE_ASSIGNMENT_REMINDER_ARRAY";
export const DELETE_ASSIGNMENT_REMINDER = "DELETE_ASSIGNMENT_REMINDER";
